import type { Metadata } from "next";
import { Inter, Dancing_Script } from "next/font/google";

// import { Cursor } from "@/shared/ui/custom-cursor";
import SplashCursor from "@/shared/ui/splash-cursor";
import { ClientOnly } from "@/shared/ui/client-only";
import { LenisProvider } from "@/shared/ui/lenis-provider";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "600", "700", "800", "900"],
  variable: "--font-inter",
});

const dancing = Dancing_Script({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-dancing",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${dancing.variable}`}>
      <body className="antialiased">
        <ClientOnly>
          <SplashCursor />
          {/* <Cursor /> */}

          <LenisProvider>{children}</LenisProvider>
        </ClientOnly>
      </body>
    </html>
  );
}
